<?php
return array (
  'title' => 'Структура свойств',
  'order' => 32,
  'menu' =>
  array (
    'layout' => 'Макет',
    'layout-break' => 'Разрыв макета (layout-break)',
    'object' => 'Объекты (object)',
    'size' => 'Размеры (size)',
    'space' => 'Отступы (space)',
    'grid' => 'Сетка (grid)',
    'flex' => 'Флексбоксы (flex)',
    'grid-flex' => 'Сетка и флексбоксы (grid-flex)',
    'typography' => 'Типографика (typography)',
    'text-color' => 'Цвет текста (text-color)',
    'text-decoration' => 'Оформление текста (text-decoration)',
    'link' => 'Ссылки (link)',
    'table' => 'Таблицы (table)',
    'svg' => 'SVG (svg)',
    'border' => 'Границы (border)',
    'divider' => 'Разделители (divider)',
    'outline' => 'Внешняя граница (outline)',
    'ring' => 'Кольцо (ring)',
    'background-image' => 'Фоновое изображение (background-image)',
    'background-color' => 'Цвет фона (background-color)',
    'gradient' => 'Градиент (gradient)',
    'stripe' => 'Полосы (stripe)',
    'theme' => 'Темы (theme)',
    'shadow' => 'Тени (shadow)',
    'filter' => 'Фильтры элемента (filter)',
    'backdrop-filter' => 'Фильтры подложки (backdrop-filter)',
    'animation' => 'Анимация (animation)',
    'scroll' => 'Прокрутка (scroll)',
    'transform' => 'Преобразования (transform)',
    'form' => 'Формы (form)',
    'interactivity' => 'Интерактивность (interactivity)',
    'print' => 'Печать (print)',
  ),
);
