<?php
return array (
  'title' => 'Property structure',
  'order' => 32,
  'menu' =>
  array (
    'layout' => 'Layout',
    'layout-break' => 'Layout break',
    'object' => 'Object',
    'size' => 'Size',
    'space' => 'Space',
    'grid' => 'Grid',
    'flex' => 'Flex',
    'grid-flex' => 'Grid and flex',
    'typography' => 'Typography',
    'text-color' => 'Text color',
    'text-decoration' => 'Text decoration',
    'link' => 'Link',
    'table' => 'Table',
    'svg' => 'SVG',
    'border' => 'Border',
    'divider' => 'Divider',
    'outline' => 'Outline',
    'ring' => 'Ring',
    'background-image' => 'Background image',
    'background-color' => 'Background color',
    'gradient' => 'Gradient',
    'stripe' => 'Stripe',
    'theme' => 'Theme',
    'shadow' => 'Shadow',
    'filter' => 'Filter',
    'backdrop-filter' => 'Backdrop filter',
    'animation' => 'Animation',
    'scroll' => 'Scroll',
    'transform' => 'Transform',
    'form' => 'Form',
    'interactivity' => 'Interactivity',
    'print' => 'Print',
  ),
);
