<?php
return array (
  'title' => 'Утилиты',
  'order' => 6,
  'menu' => 
  array (
    'layout' => 'Макет',
    'layout-break' => 'Разрыв макета',
    'objects' => 'Объекты',
    'sizes' => 'Размеры',
    'indents' => 'Отступы',
    'grid' => 'Сетка',
    'flex' => 'Флексбоксы',
    'grid-and-flexbox-utilities' => 'Утилиты для сетки и флексбоксов',
    'typography' => 'Типографика',
    'text-formatting' => 'Оформление текста',
    'links' => 'Ссылки',
    'tables' => 'Таблицы',
    'svg' => 'SVG',
    'border' => 'Граница',
    'divider' => 'Разделитель',
    'outline' => 'Внешняя граница',
    'background-image' => 'Фоновое изображение',
    'mask' => 'Маска',
    'background-gradient' => 'Градиент',
    'shadows' => 'Тени',
    'filters' => 'Фильтры элемента',
    'backdrop-filter' => 'Фильтры подложки',
    'animation' => 'Анимация',
    'overscroll' => 'Прокрутка',
    'transform' => 'Преобразования',
    'forms' => 'Формы',
    'interactivity' => 'Интерактивность',
    'print' => 'Печать',
  ),
);
