<?php

declare(strict_types=1);

$root = dirname(__DIR__);
$output = null;
foreach ($argv as $argument) {
    if (str_starts_with($argument, '--output=')) {
        $output = substr($argument, strlen('--output='));
    }
}

$paths = [];
$iterator = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($root . '/content/ru', FilesystemIterator::SKIP_DOTS),
);
foreach ($iterator as $file) {
    if ($file->isFile() && strtolower($file->getExtension()) === 'md') {
        $paths[] = $file->getPathname();
    }
}
sort($paths, SORT_STRING);

$findings = [];
$metrics = [
    'pages' => count($paths),
    'encoded_generator_markers' => 0,
    'legacy_rtags_markers' => 0,
    'escaped_html_blocks' => 0,
    'escaped_inline_code' => 0,
    'bare_image_labels' => 0,
    'missing_h1' => 0,
    'multiple_h1' => 0,
    'implicit_section_titles' => 0,
    'unbalanced_fences' => 0,
    'visible_table_markers' => 0,
    'mojibake_markers' => 0,
];

foreach ($paths as $path) {
    $relative = str_replace('\\', '/', substr($path, strlen($root) + 1));
    $markdown = (string) file_get_contents($path);
    $lines = preg_split('/\R/u', $markdown) ?: [];
    $inFence = false;
    $fence = null;
    $h1Count = 0;

    foreach ($lines as $lineNumber => $line) {
        if (preg_match('/^\s*(`{3,}|~{3,})/', $line, $match) === 1) {
            $marker = $match[1];
            if (! $inFence) {
                $inFence = true;
                $fence = $marker;
            } elseif ($fence === $marker) {
                $inFence = false;
                $fence = null;
            }
            continue;
        }
        if ($inFence) {
            continue;
        }

        $lineIndex = $lineNumber + 1;
        if (preg_match('/^#\s+\S/u', $line) === 1) {
            $h1Count++;
        }
        if (trim($line) === '&lt;!-- generated by bin/build-framework-reference.py; do not edit --&gt;') {
            addFinding($findings, $metrics, 'encoded_generator_markers', $relative, $lineIndex);
        }
        if (preg_match('/^!rtags\[[^\]]+]\s*$/u', trim($line)) === 1) {
            addFinding($findings, $metrics, 'legacy_rtags_markers', $relative, $lineIndex);
        }
        if (preg_match('/^\s*&lt;\/?(?:div|span|button|strong|code|i|section|article)\b/i', $line) === 1) {
            addFinding($findings, $metrics, 'escaped_html_blocks', $relative, $lineIndex);
        }
        preg_match_all('/`([^`\n]*)`/', $line, $inlineCode);
        $hasEscapedInlineCode = false;
        foreach ($inlineCode[1] ?? [] as $code) {
            if (preg_match('/&lt;\/?[a-z]/i', $code) === 1) {
                $hasEscapedInlineCode = true;
                break;
            }
        }
        if ($hasEscapedInlineCode) {
            addFinding($findings, $metrics, 'escaped_inline_code', $relative, $lineIndex);
        }
        if (preg_match('/^!(?!\[|rtags\[)\S.*$/u', trim($line)) === 1) {
            addFinding($findings, $metrics, 'bare_image_labels', $relative, $lineIndex);
        }
        if (preg_match('/^\s*\{\.table(?:\s+[^}]*)?}\s*$/', $line) === 1) {
            addFinding($findings, $metrics, 'visible_table_markers', $relative, $lineIndex);
        }
        if (preg_match('/�|(?:Ã|Â|Ð|Ñ)[\x{0080}-\x{00FF}]/u', $line) === 1) {
            addFinding($findings, $metrics, 'mojibake_markers', $relative, $lineIndex);
        }
    }

    if ($inFence) {
        addFinding($findings, $metrics, 'unbalanced_fences', $relative, count($lines));
    }
    if ($h1Count === 0) {
        addFinding($findings, $metrics, 'missing_h1', $relative, null);
    } elseif ($h1Count > 1) {
        addFinding($findings, $metrics, 'multiple_h1', $relative, null, ['count' => $h1Count]);
    }
}

$directories = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($root . '/content/ru', FilesystemIterator::SKIP_DOTS),
    RecursiveIteratorIterator::SELF_FIRST,
);
foreach ($directories as $directory) {
    if (! $directory->isDir()) {
        continue;
    }
    $path = $directory->getPathname();
    if ($path === $root . '/content/ru'
        || is_file($path . '/index.md')
        || is_file($path . '/section.json')
    ) {
        continue;
    }
    $ownsMarkdownPages = false;
    foreach (new DirectoryIterator($path) as $child) {
        if ($child->isFile() && strtolower($child->getExtension()) === 'md') {
            $ownsMarkdownPages = true;
            break;
        }
    }
    if ($ownsMarkdownPages) {
        $relative = str_replace('\\', '/', substr($path, strlen($root) + 1));
        addFinding($findings, $metrics, 'implicit_section_titles', $relative, null);
    }
}

$report = [
    'schema' => 'ui-doc.russian_content_audit.v1',
    'summary' => [
        'status' => $findings === [] ? 'pass' : 'needs_revision',
        'page_count' => count($paths),
        'finding_count' => count($findings),
    ],
    'metrics' => $metrics,
    'findings' => $findings,
];

$json = json_encode(
    $report,
    JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR,
) . "\n";
if (is_string($output) && $output !== '') {
    $absoluteOutput = str_starts_with($output, '/') ? $output : $root . '/' . $output;
    if (! is_dir(dirname($absoluteOutput))) {
        mkdir(dirname($absoluteOutput), 0755, true);
    }
    file_put_contents($absoluteOutput, $json);
}
echo $json;
exit($findings === [] ? 0 : 1);

/**
 * @param array<int, array<string, mixed>> $findings
 * @param array<string, int> $metrics
 * @param array<string, mixed> $extra
 */
function addFinding(
    array &$findings,
    array &$metrics,
    string $code,
    string $path,
    ?int $line,
    array $extra = [],
): void {
    $metrics[$code]++;
    $finding = ['code' => $code, 'path' => $path];
    if ($line !== null) {
        $finding['line'] = $line;
    }
    $findings[] = array_merge($finding, $extra);
}
